#! /bin/sh

sxhkd &
compton &
nm-applet &
devmon &
$HOME/scripts/plstart.sh &
wal -R &
xinput set-prop "AlpsPS/2 ALPS DualPoint TouchPad" "libinput Tapping Enabled" 1 &
xinput set-prop "AlpsPS/2 ALPS DualPoint Stick" "libinput Accel Speed" 0.7 &
setxkbmap -layout us,latam -option 'grp:alt_space_toggle' &
redshift -l 5.31921:-72.38488 -t 5700:4000 -g 0.8 -m randr -v &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         1
bspc config window_gap           0

bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
